# Generated by Django 4.1.5 on 2023-02-07 08:55
import os

from django.contrib.auth import get_user_model
from django.db import migrations

def create_superuser(apps, schema_editor):
    User = get_user_model()

    DJ_SU_EMAIL = os.environ.get('DJ_SU_EMAIL')
    DJ_SU_PASSWORD = os.environ.get('DJ_SU_PASSWORD')

    User.objects.create_superuser(
        email= DJ_SU_EMAIL,
        password=DJ_SU_PASSWORD
    )

def delete_superuser(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser)
    ]
